#!/usr/bin/env python3
"""The public package manifest: what ships, and deterministic proof it is intact.

`PACKAGE_MANIFEST.txt` used to be a list of digests somebody regenerated by hand at
the end of a phase, and the only thing checking it was a validator line reading
`check(... or True, ...)`, which is a check that cannot fail. A manifest nothing
verifies is decoration: this one drifted twenty-two entries out of date, still named
files that had moved, and omitted both maintenance commands without a single test
noticing.

So membership is DERIVED, never listed. `package_files()` walks the workspace under
an ALLOWLIST of roots, which means a new tool in `tools/` joins the package
automatically while a capture left in the repository root cannot. Under `candidate/`
only `*.example.*` may enter, so a new private authority is excluded by the SHAPE of
the rule rather than by somebody remembering to deny it. That is the same
fail-closed structure `search_profile.py` and `candidate_config.py` use for privacy,
applied to distribution.

WHAT IS DELIBERATELY OUT. The private candidate authorities (`candidate/profile.md`,
`candidate/config.json`, `candidate/cv-maintenance.md`, and everything under
`documents/`, which is the master CV and its history); the whole of `job_scraper/`,
covering live state, run captures, the job-description cache, shortlist snapshots and
the REGENERABLE official GOV.UK sponsor snapshot in `job_scraper/reference/`;
`backups/`; `reports/`; `.git/`; bytecode; and `.claude/settings.local.json`, which is
machine-local approval state.

AND THE MANIFEST ITSELF. A file cannot record its own digest, because writing the
digest changes the file. Self-reference is not an oversight to tidy up later, it is
arithmetically impossible, so it is refused at the boundary and tested for.

CRLF. The manifest is written with the platform's line endings, so it is CRLF in this
Windows workspace and LF in a POSIX checkout. Parsing strips the carriage return
rather than assuming either. A manifest that verifies on the machine that wrote it
and fails everywhere else is not an integrity boundary.
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from job_state import atomic_write_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_NAME = 'PACKAGE_MANIFEST.txt'
MANIFEST = ROOT / MANIFEST_NAME

# Directories whose contents may ship. Membership fails CLOSED: anything outside this
# allowlist needs a deliberate addition here, which is the whole point.
PACKAGE_ROOTS = ('.claude', 'candidate', 'config', 'data', 'docs', 'tools')

# Root-level files that ship, named individually because the repository root also
# holds the manifest, the private directories and whatever a session left behind.
PACKAGE_ROOT_FILES = (
    '.gitignore', 'CHANGELOG.md', 'CLAUDE.md', 'README.md',
    'UPSTREAM_LICENSE', 'UPSTREAM_NOTICE.md', 'install.ps1', 'requirements.txt',
)

# Never shipped, whatever else says otherwise.
EXCLUDED_DIR_NAMES = ('.git', '__pycache__', '.pytest_cache', 'node_modules',
                      'backups', 'reports', 'documents', 'job_scraper')
EXCLUDED_SUFFIXES = ('.pyc', '.pyo', '.tmp', '.log', '.bak')
# Private authorities, machine-local approval state, and the manifest itself.
EXCLUDED_PATHS = (
    'candidate/profile.md',
    'candidate/config.json',
    'candidate/config.proposed.json',
    'candidate/cv-maintenance.md',
    '.claude/settings.local.json',
    MANIFEST_NAME,
)
# Under these roots only the shipped TEMPLATES may enter. This is the structural half
# of the private-data rule: a new private authority nobody thought to deny is still
# excluded, because it does not match.
EXAMPLE_ONLY_ROOTS = ('candidate',)

HEX = set('0123456789abcdef')


def is_excluded(rel):
    """Whether one workspace-relative POSIX path is barred from the package."""
    rel = str(rel).replace('\\', '/')
    # `lstrip('./')` would eat the leading dot of `.claude/...`; only the exact
    # `./` prefix the manifest writes is removed.
    if rel.startswith('./'):
        rel = rel[2:]
    parts = rel.split('/')
    if any(part in EXCLUDED_DIR_NAMES for part in parts):
        return True
    if rel in EXCLUDED_PATHS:
        return True
    if any(rel.endswith(suffix) for suffix in EXCLUDED_SUFFIXES):
        return True
    if parts[0] in EXAMPLE_ONLY_ROOTS and '.example.' not in parts[-1]:
        return True
    return False


def package_files(root=None):
    """Every public package path, workspace-relative, sorted and unique.

    A set is used before sorting so one file cannot be contributed twice by two
    rules; `appears exactly once` is then a property of the data structure rather
    than a promise the caller has to keep.
    """
    root = Path(root) if root else ROOT
    found = set()
    for name in PACKAGE_ROOT_FILES:
        if (root / name).is_file() and not is_excluded(name):
            found.add(name)
    for top in PACKAGE_ROOTS:
        base = root / top
        if not base.is_dir():
            continue
        for path in base.rglob('*'):
            if not path.is_file():
                continue
            rel = path.relative_to(root).as_posix()
            if not is_excluded(rel):
                found.add(rel)
    return sorted(found)


def sha256_of(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def manifest_body(root=None):
    """The manifest text: `<sha256>  ./<path>`, sorted, one line per file."""
    root = Path(root) if root else ROOT
    return ''.join(f'{sha256_of(root / rel)}  ./{rel}\n' for rel in package_files(root))


def parse_manifest(text):
    """(entries, malformed), tolerating CRLF, LF and trailing blank lines.

    Splitting on `\\n` and stripping a trailing `\\r` handles both endings with one
    code path, which is what stops a manifest from verifying only on the platform
    that generated it.
    """
    entries, malformed = [], []
    for number, raw in enumerate(str(text).split('\n'), start=1):
        line = raw.rstrip('\r')
        if not line.strip():
            continue
        digest, separator, path = line.partition('  ')
        digest, path = digest.strip().lower(), path.strip()
        if not separator or len(digest) != 64 or not set(digest) <= HEX or not path:
            malformed.append({'line': number, 'text': line[:80]})
            continue
        entries.append({'line': number, 'sha256': digest,
                        'path': path[2:] if path.startswith('./') else path})
    return entries, malformed


def verify(root=None, manifest_path=None):
    """A structured integrity report over the manifest and the package it names."""
    root = Path(root) if root else ROOT
    manifest_path = Path(manifest_path) if manifest_path else (root / MANIFEST_NAME)
    expected = package_files(root)
    report = {
        'manifest': MANIFEST_NAME,
        'exists': manifest_path.is_file(),
        'ok': False,
        'entries': 0,
        'package_files': len(expected),
        'malformed_lines': [],
        'duplicate_entries': [],
        'forbidden_entries': [],
        'missing_files': [],
        'hash_mismatches': [],
        'unlisted_files': [],
    }
    if not report['exists']:
        report['hint'] = 'Generate it with: python tools/package_manifest.py generate'
        return report

    entries, malformed = parse_manifest(manifest_path.read_text(encoding='utf-8'))
    report['entries'] = len(entries)
    report['malformed_lines'] = malformed

    by_path = {}
    for entry in entries:
        by_path.setdefault(entry['path'], []).append(entry)
    report['duplicate_entries'] = sorted(p for p, rows in by_path.items() if len(rows) > 1)
    # A private path, an ignored path, or the manifest naming itself.
    report['forbidden_entries'] = sorted(p for p in by_path if is_excluded(p))

    for path, rows in sorted(by_path.items()):
        target = root / path
        if not target.is_file():
            report['missing_files'].append(path)
            continue
        actual = sha256_of(target)
        recorded = sorted({row['sha256'] for row in rows})
        if recorded != [actual]:
            report['hash_mismatches'].append(
                {'path': path, 'recorded': recorded, 'actual': actual})

    report['unlisted_files'] = sorted(set(expected) - set(by_path))
    report['ok'] = not any(report[field] for field in (
        'malformed_lines', 'duplicate_entries', 'forbidden_entries',
        'missing_files', 'hash_mismatches', 'unlisted_files'))
    return report


def cmd_generate(args):
    body = manifest_body()
    atomic_write_text(MANIFEST, body)
    report = verify()
    print(json.dumps({'written': True, 'manifest': MANIFEST_NAME,
                      'entries': report['entries'], 'verified': report['ok'],
                      'contains_itself': MANIFEST_NAME in body}, indent=2))
    raise SystemExit(0 if report['ok'] else 1)


def cmd_verify(args):
    report = verify()
    print(json.dumps(report, indent=2, ensure_ascii=False))
    raise SystemExit(0 if report['ok'] else 1)


def cmd_list(args):
    files = package_files()
    print(json.dumps({'count': len(files), 'files': files}, indent=2, ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser(description='Public package manifest and its verification')
    sub = parser.add_subparsers(dest='cmd', required=True)
    g = sub.add_parser('generate', help='Rewrite PACKAGE_MANIFEST.txt from the derived package.')
    g.set_defaults(func=cmd_generate)
    v = sub.add_parser('verify', help='Check every path, digest, duplicate and exclusion.')
    v.set_defaults(func=cmd_verify)
    l = sub.add_parser('list', help='The derived public package, without hashing it.')
    l.set_defaults(func=cmd_list)
    args = parser.parse_args()
    args.func(args)


if __name__ == '__main__':
    main()
